<!-- App.vue -->
<template>
  <div id="app">
    <h1>Vue App with toInterface</h1>
    <div>{{ result }}</div>
    <!-- Display the result here -->
  </div>
</template>

<script setup>
import { ref, onMounted } from "vue";
import { schemaToInterface } from "@/schemaToInterface";

// Create a ref to hold the result
const result = ref("");
const schema = {
  openapi: "3.1.0",
  info: {
    title: "Custom API",
    version: "1.0.0",
    description: "Generated by Pydantic with OpenAPI customization.",
  },
  paths: {},
  components: {
    schemas: {
      DataCollectionPaired: {
        additionalProperties: false,
        properties: {
          forward: { $ref: "#/components/schemas/DataInternalJson" },
          reverse: { $ref: "#/components/schemas/DataInternalJson" },
        },
        required: ["forward", "reverse"],
        title: "DataCollectionPaired",
        type: "object",
      },
      DataInternalJson: {
        additionalProperties: false,
        properties: {
          class: {
            const: "File",
            enum: ["File"],
            title: "Class",
            type: "string",
          },
          basename: { title: "Basename", type: "string" },
          location: { title: "Location", type: "string" },
          path: { title: "Path", type: "string" },
          listing: {
            anyOf: [
              { items: { type: "string" }, type: "array" },
              { type: "null" },
            ],
            title: "Listing",
          },
          nameroot: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Nameroot",
          },
          nameext: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Nameext",
          },
          checksum: {
            anyOf: [{ type: "string" }, { type: "null" }],
            title: "Checksum",
          },
          size: { title: "Size", type: "integer" },
        },
        required: [
          "class",
          "basename",
          "location",
          "path",
          "listing",
          "nameroot",
          "nameext",
          "checksum",
          "size",
        ],
        title: "DataInternalJson",
        type: "object",
      },
      RecursiveDataCollectionInternalJson: {
        additionalProperties: {
          anyOf: [
            { $ref: "#/components/schemas/DataInternalJson" },
            {
              $ref: "#/components/schemas/RecursiveDataCollectionInternalJson",
            },
          ],
        },
        title: "RecursiveDataCollectionInternalJson",
        type: "object",
      },
      inputs: {
        additionalProperties: false,
        properties: {
          parameter: {
            anyOf: [
              {
                items: { $ref: "#/components/schemas/DataInternalJson" },
                type: "array",
              },
              { $ref: "#/components/schemas/DataCollectionPaired" },
              {
                $ref: "#/components/schemas/RecursiveDataCollectionInternalJson",
              },
            ],
            title: "Parameter",
          },
        },
        required: ["parameter"],
        title: "",
        type: "object",
      },
    },
  },
};

// When the component mounts, call the toInterface function
onMounted(async () => {
  result.value = await schemaToInterface(schema); // Passing an example value
});
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  text-align: center;
  color: #2c3e50;
}
</style>
